export const skillPerkCatalog = [
  {
    id: "blink-aim-behind",
    name: "Backstep Vector",
    description: "Blink aims 180 degrees behind your cursor.",
    tags: ["blink"],
  },
  {
    id: "blink-target-explosion",
    name: "Blink Implosion",
    description: "Blink creates a stun explosion at the target location.",
    tags: ["blink"],
  },
  {
    id: "blink-source-explosion",
    name: "Blink Echo",
    description: "Blink creates a stun explosion at your source location.",
    tags: ["blink"],
  },
  {
    id: "blink-reload",
    name: "Tactical Warp",
    description: "Blinking instantly reloads your gun.",
    tags: ["blink"],
  },
  {
    id: "blink-fire-trail",
    name: "Scorch Line",
    description: "Blink leaves a lingering fire trail that damages enemies.",
    tags: ["blink", "fire"],
  },
  {
    id: "blink-ice-trail",
    name: "Frost Line",
    description: "Blink leaves a lingering ice trail that slows enemies.",
    tags: ["blink", "ice"],
  },
  {
    id: "blink-sword-kensei",
    name: "Kensei",
    description:
      "Blinking through enemies with your sword equipped damages them as a sword strike without advancing combo.",
    tags: ["blink", "melee"],
  },
  {
    id: "blink-three-charges",
    name: "Triple Blink",
    description: "Blink gains 3 charges and regenerates one per cooldown.",
    tags: ["blink"],
  },
  {
    id: "shout-range",
    name: "Resonant Cone",
    description: "Increase shout range.",
    tags: ["shout"],
  },
  {
    id: "shout-stun",
    name: "Concussive Voice",
    description: "Increase shout stun duration.",
    tags: ["shout"],
  },
  {
    id: "shout-reflect",
    name: "Reflective Chorus",
    description: "Shout reflects enemy projectiles.",
    tags: ["shout"],
  },
  {
    id: "shout-half-max-hp",
    name: "Thunder Lungs",
    description: "Shout deals 50% of each affected enemy's max HP as damage.",
    tags: ["shout"],
  },
  {
    id: "shout-heal-per-enemy",
    name: "War Cry Renewal",
    description: "Shout heals 10 HP for each enemy affected.",
    tags: ["shout", "survival"],
  },
  {
    id: "fireball-impact-detonation",
    name: "Impact Burst",
    description: "Fireball detonates on enemy impact.",
    tags: ["fireball", "fire"],
  },
  {
    id: "fireball-bigger-detonation",
    name: "Overpressure Core",
    description: "Fireball detonation radius and damage are increased.",
    tags: ["fireball", "fire"],
  },
  {
    id: "fireball-impact-fire-trail",
    name: "Cinder Field",
    description: "Fireball detonation spawns a lingering fire field.",
    tags: ["fireball", "fire"],
  },
  {
    id: "gun-triple-shot",
    name: "Scatter Cylinder",
    description: "Gun fires a spread of 3 bullets per shot.",
    tags: ["gun"],
  },
  {
    id: "gun-backward-shot",
    name: "Crossfire Drill",
    description: "Gun also fires backward.",
    tags: ["gun"],
  },
  {
    id: "gun-perfect-window",
    name: "Calibrated Timing",
    description: "Increase gun perfect reload window by 25%.",
    tags: ["gun"],
  },
  {
    id: "gun-kill-reload",
    name: "Battle Feed",
    description: "Killing an enemy with a gun bullet restores 1 ammo.",
    tags: ["gun"],
  },
  {
    id: "gun-bouncing-bullets",
    name: "Ricochet Rounds",
    description: "Gun bullets bounce off enemies and mountains up to 3 times.",
    tags: ["gun"],
  },
  {
    id: "gun-perfect-speed",
    name: "Flow Reload",
    description: "Perfect reload grants 10% movement speed for 1 second.",
    tags: ["gun"],
  },
  {
    id: "melee-projectile-reflect",
    name: "Deflecting Edge",
    description: "Melee slashes now reflect enemy projectiles.",
    tags: ["melee"],
  },
  {
    id: "melee-skill-cooldown-kill",
    name: "Blade Tempo",
    description: "Melee kills reduce all skill cooldowns by 10%.",
    tags: ["melee", "utility"],
  },
  {
    id: "flail-spiked-links",
    name: "Spiked Links",
    description: "Flail chain chip damage is significantly increased.",
    tags: ["flail", "melee", "chain"],
  },
  {
    id: "flail-counterweight-core",
    name: "Counterweight Core",
    description: "Flail head and chain hits deal increased damage.",
    tags: ["flail", "melee"],
  },
  {
    id: "flail-rebound-discipline",
    name: "Rebound Discipline",
    description: "Hitting different enemies in quick succession boosts flail momentum.",
    tags: ["flail", "melee", "mobility"],
  },
  {
    id: "bow-perfect-window",
    name: "Steady Draw",
    description: "Increase perfect arrow window by 25%.",
    tags: ["bow"],
  },
  {
    id: "bow-kill-reload",
    name: "Predator's Rhythm",
    description: "Arrow kills instantly finish bow reload.",
    tags: ["bow"],
  },
  {
    id: "bow-ricochet-chain",
    name: "Hunting Ricochet",
    description: "Perfect arrows no longer pierce and instead bounce to closest enemy (max 5).",
    tags: ["bow"],
  },
  {
    id: "bow-fire-arrows",
    name: "Kindled Fletching",
    description: "Arrows deal 25% extra damage and ignite trees.",
    tags: ["bow", "fire"],
  },
  {
    id: "shared-laser-pointer",
    name: "Laserpointer",
    description: "Gun and bow draw a targeting laser toward your aim.",
    tags: ["gun", "bow"],
  },
  {
    id: "pickup-magnet",
    name: "Vacuum Grip",
    description: "Pickups slowly move toward you.",
    tags: ["utility"],
  },
  {
    id: "pickup-global-cooldown-reduction",
    name: "Supply Chain",
    description: "Reduce pickup global cooldown timers by 20%.",
    tags: ["utility"],
  },
  {
    id: "utility-stunned-target-damage",
    name: "Execution Momentum",
    description: "Deal 50% more damage to stunned enemies.",
    tags: ["utility"],
  },
  {
    id: "utility-regen-half-hp",
    name: "Second Wind",
    description: "Slowly regenerate HP up to 50% max HP.",
    tags: ["utility", "survival"],
  },
];
