export const PICKUP_DEFS = {
  health: {
    type: "health",
    icon: "❤️",
    color: "rgba(255, 120, 132, 0.9)",
    radius: 11,
    lifetime: 8,
    healAmount: 10,
    weight: 34,
    globalCooldown: 1.8,
  },
  magazine: {
    type: "magazine",
    icon: "🔄",
    color: "rgba(255, 213, 123, 0.9)",
    radius: 11,
    lifetime: 8,
    weight: 22,
    globalCooldown: 4.5,
  },
  nuke: {
    type: "nuke",
    icon: "💣",
    color: "rgba(255, 166, 96, 0.95)",
    radius: 13,
    lifetime: 7,
    weight: 8,
    globalCooldown: 11,
  },
  cd: {
    type: "cd",
    icon: "⏱️",
    color: "rgba(140, 222, 255, 0.92)",
    radius: 11,
    lifetime: 8,
    weight: 14,
    globalCooldown: 7,
  },
  rage: {
    type: "rage",
    icon: "😡",
    color: "rgba(255, 98, 92, 0.95)",
    radius: 12,
    lifetime: 8,
    duration: 8,
    damageMultiplier: 1.35,
    moveSpeedMultiplier: 1.2,
    weight: 12,
    globalCooldown: 8,
    bar: {
      label: "Rage",
      color: "rgba(255, 84, 84, 0.95)",
    },
  },
  infiniteAmmo: {
    type: "infiniteAmmo",
    icon: "♾️",
    color: "rgba(255, 231, 108, 0.96)",
    radius: 12,
    lifetime: 8,
    duration: 7,
    weight: 10,
    globalCooldown: 9,
    bar: {
      label: "Infinite Ammo",
      color: "rgba(255, 226, 95, 0.95)",
    },
  },
};

export const PICKUP_POOL = Object.values(PICKUP_DEFS);