export const GAME_CONFIG = {
  canvas: {
    width: 1280,
    height: 720,
    background: "#0f1720",
  },
  ui: {
    legends: {
      pickupRows: [
        ["❤️ Health", "Restore 10 HP"],
        ["🔄 Magazine", "Reload the gun instantly"],
        ["💣 Nuke", "Expanding wipe that clears enemies"],
        ["⏱️ CD", "Refresh all skill cooldowns"],
        ["😡 Rage", "Boost damage and move speed"],
        ["♾️ Infinite Ammo", "Unlimited gun shots for a short time"],
      ],
      controlRows: [
        ["WASD", "Move"],
        ["Mouse", "Aim / attack"],
        ["1 / 2 / 3", "Sword / Gun / Bow"],
        ["Q / E / F", "Blink / Shout / Fireball"],
        ["R", "Reload"],
        ["Space", "Pause / Resume"],
      ],
    },
    pause: {
      panelBottomOffset: 184,
      panelWidth: 396,
      controlsPanelX: 34,
      pickupPanelRightOffset: 430,
    },
    title: {
      headingY: 58,
      versionY: 78,
      history: {
        maxVisibleRuns: 10,
        widthMax: 960,
        widthMargin: 180,
        height: 352,
        y: 108,
        buttonGap: 10,
        buttonY: 48,
        rowStartY: 98,
        rowHeight: 24,
      },
      startButton: {
        width: 260,
        height: 36,
        bottomOffset: 64,
      },
      libraryToggle: {
        width: 192,
        height: 30,
        rightOffset: 230,
        bottomOffset: 58,
      },
      controlsPanel: {
        x: 34,
        width: 396,
        bottomOffset: 184,
      },
    },
    perkLibrary: {
      modalInsetX: 58,
      modalInsetY: 44,
      closeButton: {
        width: 110,
        height: 28,
        topOffset: 16,
        rightOffset: 130,
      },
      filter: {
        x: 20,
        y: 56,
        width: 220,
        height: 28,
        optionHeight: 24,
      },
      cards: {
        topOffset: 98,
        bottomOffset: 56,
        gap: 10,
        height: 56,
      },
      scroll: {
        trackRightOffset: 12,
        trackWidth: 6,
        minThumbHeight: 36,
      },
    },
  },
  perks: {
    tags: ["projectile", "precision", "aoe", "chain", "survival", "reload", "mobility"],
    synergyFactor: 3,
    penaltyFactor: 2,
    tierCount: 8,
    applyHealOnPickup: 8,
    minBaseMaxHp: 40,
    libraries: {
      projectile: {
        prefix: "Ballistic",
        description: "Boosts projectile damage and velocity.",
        damageBase: 0.03,
        damagePerTier: 0.01,
        speedBase: 0.02,
        speedPerTier: 0.01,
      },
      precision: {
        prefix: "Marksman",
        description: "Increases crit chance and tightens spread.",
        critBase: 0.015,
        critPerTier: 0.004,
        critCap: 0.55,
        spreadReduction: 0.025,
        spreadMin: 0.35,
      },
      aoe: {
        prefix: "Shockwave",
        description: "Adds area damage radius to hits.",
        radiusBase: 6,
        radiusPerTier: 1.5,
      },
      chain: {
        prefix: "Arc",
        description: "Adds chance to chain lightning to nearby enemies.",
        chanceBase: 0.015,
        chancePerTier: 0.003,
        chanceCap: 0.5,
      },
      survival: {
        prefix: "Bulwark",
        description: "Raises max HP and grants minor lifesteal.",
        hpBase: 5,
        hpPerTier: 2,
        lifestealBase: 0.004,
        lifestealPerTier: 0.001,
        lifestealCap: 0.22,
      },
      reload: {
        prefix: "Tactical",
        description: "Improves reload speed and magazine size.",
        reloadBase: 0.05,
        reloadPerTier: 0.015,
        ammoEveryEvenTier: 1,
      },
      mobility: {
        prefix: "Strider",
        description: "Increases movement and pickup radius.",
        speedBase: 0.04,
        speedPerTier: 0.01,
        pickupBase: 2,
        pickupPerTier: 1,
      },
    },
    special: {
      frenziedRitual: {
        fireRate: 0.35,
        maxHpPenalty: 6,
      },
      vampireCircuit: {
        lifeSteal: 0.08,
        lifeStealCap: 0.3,
      },
      kineticPrism: {
        damage: 0.14,
        projectileSpeed: 0.12,
        chainChance: 0.06,
        chainCap: 0.5,
      },
      combatTrance: {
        moveSpeed: 0.12,
        spreadReduction: 0.1,
        spreadMin: 0.3,
      },
    },
  },
  balance: {
    xpScaling: 1.5,
    spawnScaling: 0.02,
    healDropChance: 0.1,
    baseEnemyContactDamage: 14,
    projectileSpeed: 740,
    projectileLifetime: 1.4,
  },
  player: {
    speed: 280,
    radius: 16,
    baseHp: 100,
    baseXpToNext: 60,
    levelUpXpMultiplier: 1.5,
    baseCritMultiplier: 1.5,
    levelUpPerkPoints: 1,
    perkSelectionLockDuration: 0.5,
    gameOverAnimationTime: 1.1,
  },
  drops: {
    heal: {
      baseValue: 8,
      difficultyScale: 0.4,
      lifetime: 5,
      radius: 10,
      pickupBaseBonus: 12,
    },
  },
  skills: {
    blink: {
      key: "q",
      icon: "💨",
      label: "Blink",
      distance: 200,
      cooldown: 5,
      effect: {
        radius: 10,
        duration: 0.28,
        growth: 26,
        color: "120, 226, 255",
      },
    },
    shout: {
      key: "e",
      icon: "🗣️",
      label: "Shout",
      cooldown: 10,
      radius: 250,
      stunDuration: 1,
      screenShake: 1.8,
      screenFlash: 0.1,
      reflectMinSpeed: 340,
      reflectColor: "#8ff8ff",
      reflectedLifetimeMin: 1.2,
      wave: {
        duration: 0.34,
        thickness: 42,
      },
      castEffect: {
        radius: 20,
        duration: 0.28,
        growth: 36,
        color: "160, 250, 245",
      },
      reflectImpactEffect: {
        radius: 8,
        duration: 0.16,
        growth: 18,
        color: "170, 255, 246",
      },
      stunImpactEffect: {
        duration: 0.22,
        growth: 20,
        color: "180, 244, 255",
      },
    },
    fireball: {
      key: "f",
      icon: "🔥",
      label: "Fireball",
      cooldown: 7,
      speed: 280,
      radius: 16,
      directDamage: 26,
      splashDamage: 38,
      splashRadius: 132,
      lifetime: 3,
      castEffect: {
        radius: 12,
        duration: 0.24,
        growth: 22,
        color: "255, 168, 98",
      },
      detonation: {
        screenShake: 2.8,
        screenFlash: 0.16,
        hitStop: 0.035,
        effects: [
          { radius: 16, duration: 0.3, growth: 46, color: "255, 158, 92" },
          { radiusFactor: 0.42, duration: 0.48, growth: 36, color: "255, 216, 120" },
          { radius: 18, duration: 0.24, growth: 22, color: "255, 244, 186" },
        ],
      },
    },
  },
  weapons: {
    gun: {
      type: "projectile",
      damage: 18,
      fireRate: 6,
      spread: 0.045,
      magazineSize: 12,
      reloadTime: 1.6,
      perfectReloadWindow: [0.45, 0.6],
      projectileSpeedMultiplier: 1.22,
      ammoBarDuration: 0.8,
      reloadFeedback: {
        perfectDuration: 0.28,
        missDuration: 0.4,
      },
    },
    bow: {
      chargeWindow: [0.7, 0.8],
      chargeTime: 1.05,
      reloadTime: 0.5,
      minDamage: 22,
      maxDamage: 70,
      minSpeed: 520,
      maxSpeed: 980,
      fullChargeThreshold: 0.98,
      perfectStrength: 1,
      fullChargeStrength: 0.82,
      strengthBase: 0.06,
      strengthScale: 0.34,
      projectileLifetime: 1.8,
      cooldown: 0.16,
      perfectRadius: 6,
      normalRadius: 5,
      perfectPierce: 999,
      perfectColor: "#8afff4",
      normalColor: "#9be2ff",
    },
    melee: {
      comboResetTime: 0.72,
      combo: [
        {
          damage: 28,
          range: 74,
          innerRange: 16,
          arc: Math.PI * 0.92,
          startup: 0.065,
          duration: 0.24,
          cooldown: 0.3,
          color: "110, 244, 255",
        },
        {
          damage: 34,
          range: 88,
          innerRange: 20,
          arc: Math.PI * 0.72,
          startup: 0.085,
          duration: 0.27,
          cooldown: 0.34,
          color: "142, 255, 186",
        },
        {
          damage: 46,
          range: 102,
          innerRange: 24,
          arc: Math.PI * 0.62,
          startup: 0.11,
          duration: 0.31,
          cooldown: 0.42,
          color: "255, 228, 124",
        },
      ],
    },
  },
  enemies: {
    spawn: {
      recycleDistanceMultiplier: 1.8,
      offscreenRespawnAfter: 2.8,
      randomRespawnDelay: { min: 0.45, max: 1.35 },
      aggressiveRespawnDelay: { min: 0.08, max: 0.28 },
      spawnPadding: 120,
      offscreenPadding: 40,
      movementLookAhead: {
        speedThreshold: 25,
        speedMax: 340,
        base: 110,
        extra: 120,
      },
      rateBase: 0.55,
      rateStageScale: 0.16,
      rateDifficultyScale: 0.9,
      maxEnemiesBase: 10,
      maxEnemiesStageScale: 4,
      maxEnemiesDifficultyScale: 6,
      weights: [
        { type: "chaser", weight: 42, minStage: 1 },
        { type: "slime", weight: 14, minStage: 1, options: { tier: 0 } },
        { type: "shooter", weight: 20, minStage: 1 },
        { type: "assaultShooter", weight: 13, minStage: 1 },
        { type: "shotgunShooter", weight: 11, minStage: 1 },
        { type: "bomber", weight: 12, minStage: 1 },
        { type: "mortar", weight: 8, minStage: 1 },
        { type: "flyingBomber", weight: 7, minStage: 1 },
      ],
    },
    ai: {
      predictiveAimChance: 0.45,
      mortarDangerRadius: 64,
      mortarTelegraphDuration: 0.72,
      mortarTargetSpread: 96,
      mortarTargetJitter: 54,
      bomberSlowFactorWhenPrimed: 0.45,
      spawnBoostMultiplier: 1.45,
      spawnBoostTime: { min: 2, max: 3 },
      enemySeparationIterations: 2,
      enemySeparationStrength: 0.85,
      enemySeparationPaddingFactor: 0.94,
    },
    archetypes: {
      chaser: {
        hpBase: 30,
        hpDifficultyScale: 2,
        speedBase: 150,
        speedDifficultyScale: 3,
        radius: 14,
        color: "#ff8a9f",
        contactDamage: 14,
        xp: 10,
      },
      shooter: {
        hpBase: 42,
        hpDifficultyScale: 3,
        speedBase: 120,
        speedDifficultyScale: 2,
        radius: 16,
        color: "#ffb574",
        fireCooldown: 1.4,
        preferredDistance: 210,
        contactDamage: 16,
        xp: 16,
        projectile: { speed: 340, damage: 11, lifetime: 2.6, radius: 5, color: "#ff8d6d" },
      },
      assaultShooter: {
        hpBase: 36,
        hpDifficultyScale: 3,
        speedBase: 134,
        speedDifficultyScale: 2,
        radius: 15,
        color: "#ff996d",
        fireCooldown: 2.3,
        preferredDistance: 250,
        burstCount: 10,
        burstInterval: 0.07,
        waveAmplitude: 30,
        waveFrequency: 1.15,
        aimJitter: 0.04,
        contactDamage: 12,
        xp: 20,
        projectile: { speed: 360, damage: 7, lifetime: 2.2, radius: 4, color: "#ff9f7a", speedVariance: 0.1 },
      },
      shotgunShooter: {
        hpBase: 38,
        hpDifficultyScale: 3,
        speedBase: 126,
        speedDifficultyScale: 2,
        radius: 16,
        color: "#ff7f5f",
        fireCooldown: 1.8,
        preferredDistance: 190,
        pelletCount: 7,
        pelletSpread: 0.55,
        contactDamage: 14,
        xp: 22,
        projectile: { speed: 320, damage: 6, lifetime: 1.3, radius: 4, color: "#ff8c66" },
      },
      mortar: {
        hpBase: 52,
        hpDifficultyScale: 4,
        speedBase: 92,
        speedDifficultyScale: 1,
        radius: 18,
        color: "#f09a6a",
        throwCooldown: 2.5,
        throwTimer: 0.7,
        preferredDistance: 330,
        throwRange: 520,
        contactDamage: 20,
        xp: 30,
        impactDamage: 20,
      },
      bomber: {
        hpBase: 24,
        hpDifficultyScale: 2,
        speedBase: 220,
        speedDifficultyScale: 4,
        radius: 12,
        color: "#ff6a82",
        contactDamage: 10,
        explosionRadius: 78,
        explosionDamage: 24,
        detonationRange: 46,
        fuseDuration: 0.22,
        xp: 18,
        deathEffects: {
          screenShake: 2.2,
          screenFlash: 0.2,
          effects: [
            { radius: 16, duration: 0.34, growth: 34, color: "255, 118, 140" },
            { radiusFactor: 0.52, duration: 0.45, growth: 14, color: "255, 190, 162" },
          ],
        },
      },
      flyingBomber: {
        hpBase: 32,
        hpDifficultyScale: 3,
        radius: 11,
        color: "#ff2244",
        flySpeed: 840,
        warningDuration: 1.2,
        bombInterval: 120,
        bombRadius: 72,
        bombDamage: 22,
        bombTelegraphDuration: 0.38,
        contactDamage: 20,
        xp: 28,
      },
      slime: {
        maxTier: 3,
        splitCount: 2,
        hpByTier: [34, 20, 12, 7],
        hpDifficultyScaleByTier: [1.4, 1.2, 1, 0.8],
        speedByTier: [95, 118, 142, 164],
        radiusByTier: [18, 13, 9, 6],
        xpByTier: [18, 10, 6, 3],
        contactDamageByTier: [16, 11, 8, 6],
        colorByTier: ["#7ded8f", "#65d97f", "#55bf70", "#44a862"],
      },
    },
  },
  world: {
    chunkSize: 480,
    maxChunkCache: 140,
    obstaclePadding: 86,
    visiblePadding: 80,
    mountains: {
      countMaxExclusive: 3,
      radiusMin: 34,
      radiusRange: 32,
      edgePadding: 50,
      spacing: 24,
      attempts: 8,
    },
    trees: {
      countBase: 3,
      countRange: 6,
      radiusMin: 14,
      radiusRange: 13,
      edgePadding: 30,
      spacing: 10,
      attempts: 8,
      slowMultiplier: 0.55,
      burnDuration: 3.5,
      burnDamagePerSecond: 18,
    },
  },
};
