import { BALANCE, CANVAS, GAME_CONFIG } from "./constants.js";

export function createInitialState() {
  return {
    running: false,
    paused: true,
    titleScreen: true,
    gameOver: false,
    gameOverElapsed: 0,
    time: 0,
    waveTimer: 0,
    notifications: [],

    player: {
      x: CANVAS.width * 0.5,
      y: CANVAS.height * 0.5,
      hp: GAME_CONFIG.player.baseHp,
      maxHp: GAME_CONFIG.player.baseHp,
      xp: 0,
      level: 1,
      xpToNext: GAME_CONFIG.player.baseXpToNext,
      radius: BALANCE.playerRadius,
      speed: BALANCE.playerSpeed,
      tagCounts: {
        projectile: 0,
        precision: 0,
        aoe: 0,
        chain: 0,
        survival: 0,
        reload: 0,
        mobility: 0,
      },
      ownedPerks: [],
      ownedPerkIds: new Set(),
      perkChoices: [],
      perkPoints: 0,
      perkModalOpen: false,
      perkRerollAvailable: false,
      perkRerollAnimationTimer: 0,
      perkRerollRect: null,
      perkSelectionLockTimer: 0,
      damageMultiplier: 1,
      fireRateMultiplier: 1,
      projectileSpeedMultiplier: 1,
      spreadMultiplier: 1,
      maxHpBonus: 0,
      lifeSteal: 0,
      moveSpeedMultiplier: 1,
      reloadSpeedMultiplier: 1,
      ammoCapacityBonus: 0,
      critChance: 0,
      critMultiplier: GAME_CONFIG.player.baseCritMultiplier,
      chainChance: 0,
      aoeRadius: 0,
      pickupRadiusBonus: 0,
      pickupMagnetEnabled: false,
      rageTimer: 0,
      infiniteAmmoTimer: 0,
      hasInfiniteAmmo: false,
      pickupDamageMultiplier: 1,
      pickupMoveSpeedMultiplier: 1,
      activeDurationBars: [],
      blinkDistance: GAME_CONFIG.skills.blink.distance,
      blinkCooldown: GAME_CONFIG.skills.blink.cooldown,
      blinkCharges: 1,
      blinkMaxCharges: 1,
      blinkChargeTimer: 0,
      blinkCooldownRemaining: 0,
      blinkAimsBehind: false,
      blinkExplosionAtTarget: false,
      blinkExplosionAtSource: false,
      blinkReloadsGun: false,
      blinkLeavesFireTrail: false,
      blinkLeavesIceTrail: false,
      shoutCooldown: GAME_CONFIG.skills.shout.cooldown,
      shoutCooldownRemaining: 0,
      shoutRadius: GAME_CONFIG.skills.shout.radius,
      shoutRangeBonus: 0,
      shoutStunDurationBonus: 0,
      shoutReflectProjectiles: false,
      shoutPreview: {
        active: false,
      },
      fireballCooldown: GAME_CONFIG.skills.fireball.cooldown,
      fireballCooldownRemaining: 0,
      fireballDetonateOnImpact: false,
      fireballDetonationRadiusMultiplier: 1,
      fireballDetonationDamageMultiplier: 1,
      fireballSpawnsFireField: false,
      gunTripleShot: false,
      gunPerfectWindowMultiplier: 1,
      gunKillRestoresAmmo: false,
      gunBulletBounces: false,
      gunPerfectReloadMoveSpeedBoost: false,
      meleeReflectProjectiles: false,
      swordSkillCooldownOnKill: false,
      bowPerfectWindowMultiplier: 1,
      bowKillInstantReload: false,
      bowRicochetToClosestEnemy: false,
      weaponLaserPointer: false,
      pickupGlobalCooldownMultiplier: 1,
      moveSpeedTemporaryMultiplier: 1,
      perfectReloadMoveBoostTimer: 0,
      blinkPreview: {
        active: false,
        x: 0,
        y: 0,
      },
      aim: {
        x: CANVAS.width * 0.5 + 120,
        y: CANVAS.height * 0.5,
      },
    },

    enemies: [],
    projectiles: [],
    indicators: [],
    drops: [],
    effects: [],
    floatingTexts: [],
    slashEffects: [],
    shoutWaves: [],
    fireballs: [],
    lingeringZones: [],
    nukeWaves: [],
    pickupTypeCooldowns: {},
    screenFx: {
      shake: 0,
      damageFlash: 0,
      actionFlash: 0,
      hitStop: 0,
    },
    runStats: {
      startedAt: 0,
      kills: 0,
      recorded: false,
    },
    runHistory: [],
    runHistorySort: "latest",
    appVersion: "0.0",
    perkProgress: {
      seen: {},
      activated: {},
    },
    titlePerkLibraryOpen: false,
    titlePerkLibraryFilter: "all",
    titlePerkLibraryScrollOffset: 0,
    titlePerkLibraryScrollMax: 0,
    titlePerkLibraryDragging: false,
    titlePerkLibraryDragLastY: 0,
    titleStartRect: null,
    titleSortRects: [],
    titlePerkLibraryToggleRect: null,
    titlePerkLibraryModalRect: null,
    titlePerkLibraryScrollAreaRect: null,
    titlePerkLibraryCloseRect: null,
    titlePerkLibraryFilterRect: null,
    titlePerkLibraryFilterDropdownOpen: false,
    titlePerkLibraryFilterRects: [],

    systems: {},
  };
}
